#document settings
title: Document Title Here
description: Document Description
url: http://gbinal.github.com/slash-developer-kit/
repo_url: http://www.github.com/gbinal/slash-developer-kit/

# default build settings for running locally, no need to edit
server: auto
safe: true
pymgemnts: true
auto: true