#document settings
title: /Developer Kit
description: The elements that make up a well-rounded developer hub.
url: http://gbinal.github.com/slash-developer-kit
repo_url: http://github.com/gbinal/slash-developer-kit

# default build settings for running locally, no need to edit
server: auto
safe: true
pymgemnts: true
auto: true